### ISSUE TITLE
[bug] Missing messages when running in clusters

### ISSUE THREAD

**Issue by robertsLando** [mcollina/mqemitter-mongodb#17]
See https://github.com/moscajs/aedes-tests/pull/5#issuecomment-616449835

**Comment by mcollina** [comment]
That'd be interesting to fix! Have you got any ideas?

**Comment by robertsLando** [comment]
I'm investigating on this... I can't find any docs in mongodb about tailable capped collections in clusters with mentions about data loss. Also the problem could be here: https://github.com/mcollina/mqemitter-mongodb/blob/master/mqemitter-mongodb.js#L190

Do you have any ideas @mcollina ?

**Comment by mcollina** [comment]
I don't have time to look into this :/

**Comment by robertsLando** [comment]
Based on a question that I opened on mongodb forum: 

https://developer.mongodb.com/community/forums/t/mongodb-pub-sub-using-tailable-cursors-in-nodejs-with-clusters/3027/2


Seems that talable cursors are not so good with clusters, I will submit a fix based on this suggestion but that will require mongodb >= 3.6. So what do you suggest? Check mongodb version and use this method if possible and keep the old one as a fallback?
---

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by mcollina** [comment]
Ok, we'll bump a major!

**Comment by robertsLando** [comment]
I have found a fix, with this everything works with clusters and there is no need of major updates, just a patch :smile:
