### ISSUE TITLE
[question] Use Map instead of Object for waiting 

### ISSUE THREAD

**Issue by robertsLando** [mcollina/mqemitter-mongodb#25]
Could we use Map instead of object [here](https://github.com/mcollina/mqemitter-mongodb/blob/master/mqemitter-mongodb.js#L83) ?

Could this have any performance benefit?

**Comment by robertsLando** [comment]
@mcollina

**Comment by mcollina** [comment]
..maybe? You'd need to benchmark. Map and object are backed by the same data structures in V8 with some difference in the marshalling logic from JS.

**Comment by robertsLando** [comment]
AFAIK the delete operation is much better in Maps, but your nodejs core knowledge is far way better than mine :) I could submit a PR for this.

**Comment by mcollina** [comment]
Yes it is!

**Comment by robertsLando** [comment]
Can close this too @mcollina
