### ISSUE TITLE
Tests fails on Mac 50% of the time

### ISSUE THREAD

**Issue by mcollina** [mcollina/mqemitter-mongodb#27]
I'm not sure why, but the first test of `abstractTests.js` fails.

**Comment by mcollina** [comment]
cc @robertsLando

**Comment by robertsLando** [comment]
@mcollina I'm not able to reproduce this on my laptop, could you give me more info about the fail?

Could you test also the previous version to see if test fails in that too?

**Comment by mcollina** [comment]
They all fail for some reason. Are you using mongodb inside docker as defined in package.json?

**Comment by robertsLando** [comment]
Nope, I'm using mongo db installed on Ubuntu 18.04. I just add a command on mongodb to reduce the ttl checks to 2 seconds like we do in docker but that is just for test purposes (without that the test would take some minutes to end)

**Comment by mcollina** [comment]
I do not have the problem on Ubuntu, only on Mac.

**Comment by robertsLando** [comment]
Sincerly I have no idea Matteo, I don't own a Mac :( just a tought: it could be that persistence is not ready when the test starts ("stream" event isn't emitted)?
